image: Visual Studio 2015
version: "1.0.0-development-{build}"
configuration:
  - Release

init:
  - git config --global core.autocrlf input

test: off

before_build:
  - ps: .\Set-PackageLabel.ps1
  - dotnet restore -v minimal

build:
  project: AspNetCoreRateLimit.sln
  parallel: true
  verbosity: minimal

after_build:
  - dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts .\src\AspNetCoreRateLimit\project.json

artifacts:
  - path: artifacts\*.nupkg
